version: '3.8'
services:
  web:
    depends_on:
      - postgres_db
    ports:
      - 8006:8000
    env_file:
      - web/.env
    build: 
      context: ./web/
      dockerfile: Dockerfile
    volumes:
      -./api/main:/app/main/
  
  postgres_db:
    image: postgres 
    restart : always
    env_file:
      - web/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: