version: '3.8'
services:
  db:
    container_name: pdb
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${FILM_USER}
      POSTGRES_PASSWORD: ${FILM_PWD}
      POSTGRES_DB: ${FILM_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  scrap:
    container_name: scrap
    # image: 
    build: .
    env_file:
      - .env
    command: python -m http.server 8000
    volumes:
      - .:/home/app
    ports:
      - 8000:8000
