# Generated by Django 5.0.4 on 2024-04-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmScrap',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('year', models.IntegerField(max_length=4)),
                ('director', models.JSONField()),
                ('rating_press', models.FloatField()),
                ('rating_public', models.FloatField()),
                ('casting', models.JSONField()),
                ('synopsis', models.TextField()),
                ('distributor', models.CharField(max_length=255)),
                ('budget', models.BigIntegerField()),
                ('lang', models.JSONField()),
                ('visa', models.IntegerField()),
                ('award', models.IntegerField(max_length=4)),
                ('thumbnail', models.URLField()),
            ],
        ),
    ]
