# Generated by Django 4.2.11 on 2024-04-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmscrap',
            name='casting',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='lang',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
