# Generated by Django 4.2.11 on 2024-04-04 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Functionalities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_semaine', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionalities.genre')),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionalities.historique')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionalities.film')),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionalities.historique')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionalities.country')),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionalities.historique')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueCasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionalities.casting')),
                ('historique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Functionalities.historique')),
            ],
        ),
    ]
