# Generated by Django 4.2.11 on 2024-04-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0002_historique_historiquegenre_historiquefilm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='portrait',
            field=models.URLField(blank=True, null=True),
        ),
    ]
