# Generated by Django 5.0.4 on 2024-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0002_filmscrap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmscrap',
            name='award',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='budget',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='casting',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='director',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='lang',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='rating_press',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='rating_public',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='visa',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='year',
            field=models.SmallIntegerField(null=True),
        ),
    ]
