# Generated by Django 4.2.11 on 2024-04-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0002_alter_filmscrap_casting_alter_filmscrap_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmscrap',
            name='casting',
            field=models.JSONField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='director',
            field=models.JSONField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='genre',
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
