# Generated by Django 5.0.4 on 2024-04-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0003_alter_filmscrap_award_alter_filmscrap_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmscrap',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmscrap',
            name='distributor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
