# Generated by Django 4.2.11 on 2024-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0003_alter_film_portrait'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='realisateurs',
            field=models.ManyToManyField(related_name='films', to='Functionalities.realisateur'),
        ),
    ]
