# Generated by Django 4.2.11 on 2024-04-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0003_alter_filmscrap_casting_alter_filmscrap_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmscrap',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
