# Generated by Django 5.0.4 on 2024-04-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0004_filmscrap_title_alter_filmscrap_distributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmscrap',
            old_name='director',
            new_name='director_allo',
        ),
        migrations.RenameField(
            model_name='filmscrap',
            old_name='url',
            new_name='url_allo',
        ),
        migrations.RenameField(
            model_name='filmscrap',
            old_name='year',
            new_name='year_allo',
        ),
    ]
