# Generated by Django 4.2.11 on 2024-04-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0004_alter_filmscrap_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmscrap',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
