# Generated by Django 5.0.4 on 2024-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0005_rename_director_filmscrap_director_allo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmscrap',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
