# Generated by Django 5.0.4 on 2024-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0006_alter_filmscrap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmscrap',
            name='director_raw',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='filmscrap',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='filmscrap',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
