# Generated by Django 5.0.4 on 2024-04-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Functionalities', '0007_filmscrap_director_raw_filmscrap_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmscrap',
            name='genre',
            field=models.JSONField(null=True),
        ),
    ]
