version: '3.8'
services:
  webapp:
    container_name: webapp
    env_file:
      - .env
    environment:
      ENVIRONMENT: dev
      DEBUG: 1
      GUNICORN_BIND_ADDRESS: 0.0.0.0:8000
    restart: always
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ./manage.py runserver 0.0.0.0:8000
