"""update allo

Revision ID: 0f4a157a5f7f
Revises: 198e81b731f6
Create Date: 2024-03-29 17:45:10.795153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0f4a157a5f7f'
down_revision: Union[str, None] = '198e81b731f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films_allo',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_jp', sa.String(length=255), nullable=False),
    sa.Column('synopsis', mysql.TEXT(), nullable=True),
    sa.Column('distributor', sa.String(length=100), nullable=True),
    sa.Column('casting', mysql.JSON(), nullable=True),
    sa.Column('rating_press', mysql.FLOAT(), nullable=True),
    sa.Column('rating_public', mysql.FLOAT(), nullable=True),
    sa.Column('award', mysql.INTEGER(), nullable=True),
    sa.Column('budget', mysql.INTEGER(), nullable=True),
    sa.Column('lang', mysql.JSON(), nullable=True),
    sa.Column('visa', mysql.INTEGER(), nullable=True),
    sa.Column('time_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_allo_id'), 'films_allo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_allo_id'), table_name='films_allo')
    op.drop_table('films_allo')
    # ### end Alembic commands ###
