"""film sortie

Revision ID: 37b03d5e1059
Revises: c37e053e9692
Create Date: 2024-04-03 13:40:16.249882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '37b03d5e1059'
down_revision: Union[str, None] = 'c37e053e9692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films_sortie',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_jp', sa.String(length=255), nullable=False),
    sa.Column('url_allo', sa.String(length=255), nullable=False),
    sa.Column('director_allo', mysql.JSON(), nullable=True),
    sa.Column('year_allo', mysql.INTEGER(display_width=4), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('synopsis', mysql.TEXT(), nullable=True),
    sa.Column('distributor', sa.String(length=100), nullable=True),
    sa.Column('casting', mysql.JSON(), nullable=True),
    sa.Column('rating_press', mysql.FLOAT(), nullable=True),
    sa.Column('rating_public', mysql.FLOAT(), nullable=True),
    sa.Column('award', mysql.INTEGER(), nullable=True),
    sa.Column('budget', mysql.BIGINT(), nullable=True),
    sa.Column('lang', mysql.JSON(), nullable=True),
    sa.Column('visa', mysql.INTEGER(), nullable=True),
    sa.Column('time_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_sortie_id'), 'films_sortie', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_sortie_id'), table_name='films_sortie')
    op.drop_table('films_sortie')
    # ### end Alembic commands ###
