"""0.0.1

Revision ID: 3b867a5bae0b
Revises: 
Create Date: 2024-04-02 07:51:48.596738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3b867a5bae0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films_allo',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('id_jp', sa.String(length=255), nullable=False),
    sa.Column('synopsis', mysql.TEXT(), nullable=True),
    sa.Column('distributor', sa.String(length=100), nullable=True),
    sa.Column('casting', mysql.JSON(), nullable=True),
    sa.Column('rating_press', mysql.FLOAT(), nullable=True),
    sa.Column('rating_public', mysql.FLOAT(), nullable=True),
    sa.Column('award', mysql.INTEGER(), nullable=True),
    sa.Column('budget', mysql.INTEGER(), nullable=True),
    sa.Column('lang', mysql.JSON(), nullable=True),
    sa.Column('visa', mysql.INTEGER(), nullable=True),
    sa.Column('time_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_allo_id'), 'films_allo', ['id'], unique=False)
    op.create_table('films_jp',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=False),
    sa.Column('raw_title', sa.String(length=255), nullable=False),
    sa.Column('raw_director', sa.String(length=255), nullable=False),
    sa.Column('url_jp', sa.String(length=255), nullable=False),
    sa.Column('year', mysql.INTEGER(display_width=4), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('duration', mysql.INTEGER(display_width=6), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('first_day', mysql.INTEGER(display_width=9), nullable=True),
    sa.Column('first_weekend', mysql.INTEGER(display_width=9), nullable=True),
    sa.Column('first_week', mysql.INTEGER(display_width=9), nullable=True),
    sa.Column('hebdo_rank', mysql.INTEGER(display_width=9), nullable=True),
    sa.Column('total_spectator', mysql.INTEGER(display_width=9), nullable=True),
    sa.Column('copies', mysql.INTEGER(display_width=6), nullable=True),
    sa.Column('time_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_jp_id'), 'films_jp', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_jp_id'), table_name='films_jp')
    op.drop_table('films_jp')
    op.drop_index(op.f('ix_films_allo_id'), table_name='films_allo')
    op.drop_table('films_allo')
    # ### end Alembic commands ###
