"""film sortie remove id_jp

Revision ID: 8b7cbb281da8
Revises: 37b03d5e1059
Create Date: 2024-04-03 13:44:59.099330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8b7cbb281da8'
down_revision: Union[str, None] = '37b03d5e1059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films_sortie', 'id_jp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films_sortie', sa.Column('id_jp', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
