"""0.0.1

Revision ID: e74e2ac74332
Revises: 
Create Date: 2024-03-29 10:50:10.349870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e74e2ac74332'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=False),
    sa.Column('year', mysql.INTEGER(display_width=4), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('duration', mysql.INTEGER(display_width=6), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('first_day', mysql.INTEGER(display_width=6), nullable=True),
    sa.Column('first_weekend', mysql.INTEGER(display_width=6), nullable=True),
    sa.Column('first_week', mysql.INTEGER(display_width=6), nullable=True),
    sa.Column('hebdo_rank', mysql.INTEGER(display_width=6), nullable=True),
    sa.Column('copies', mysql.INTEGER(display_width=6), nullable=True),
    sa.Column('time_created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('time_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_id'), 'films', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_id'), table_name='films')
    op.drop_table('films')
    # ### end Alembic commands ###
